import { SlidersHorizontal } from "lucide-react";
import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ProductCard } from "@/components/store/product-card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { products, type Category } from "@/lib/products";
export const Route = createFileRoute("/shop")({ head: () => ({ meta: [{ title: "Shop — RŌSEN" }, { name: "description", content: "Shop RŌSEN furniture, lighting, textiles, décor and outdoor pieces." }, { property: "og:title", content: "Shop — RŌSEN" }, { property: "og:description", content: "A considered collection for quieter homes." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ShopPage });
const categories = ["All", "Furniture", "Lighting", "Textiles", "Décor", "Outdoor"] as const;
const bands = [{ value: "all", label: "All prices", min: 0, max: Infinity }, { value: "4-8", label: "₹4,000–₹8,000", min: 4000, max: 8000 }, { value: "8-12", label: "₹8,000–₹12,000", min: 8001, max: 12000 }, { value: "12-16", label: "₹12,000–₹16,000", min: 12001, max: 16000 }, { value: "16-20", label: "₹16,000–₹20,000", min: 16001, max: 20000 }, { value: "20-24", label: "₹20,000–₹24,000", min: 20001, max: 24000 }];
function ShopPage() { const [category, setCategory] = useState<(typeof categories)[number]>("All"); const [band, setBand] = useState("all"); const [sort, setSort] = useState("featured");
  const visible = useMemo(() => { const range = bands.find((item) => item.value === band) ?? bands[0]; const next = products.filter((p) => (category === "All" || p.category === category as Category) && p.price >= range.min && p.price <= range.max); if (sort === "newest") return [...next].reverse(); if (sort === "low") return [...next].sort((a,b) => a.price-b.price); if (sort === "high") return [...next].sort((a,b) => b.price-a.price); return next; }, [category, band, sort]);
  return <div className="site-container"><header className="page-intro border-b"><p className="eyebrow">The complete collection</p><h1 className="mt-4 font-display text-5xl sm:text-6xl">Shop</h1><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Enduring forms and natural materials, selected for rooms that feel lived in.</p></header>
    <div className="flex flex-wrap items-center gap-3 py-6"><SlidersHorizontal className="mr-1 size-4"/><div className="flex max-w-full gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`h-9 whitespace-nowrap border px-4 text-xs ${category === item ? "border-foreground bg-foreground text-background" : "border-border"}`}>{item}</button>)}</div><div className="ml-auto grid w-full grid-cols-2 gap-2 sm:w-auto"><Select value={band} onValueChange={setBand}><SelectTrigger aria-label="Price range" className="min-w-36"><SelectValue /></SelectTrigger><SelectContent>{bands.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort products" className="min-w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="featured">Featured</SelectItem><SelectItem value="newest">Newest</SelectItem><SelectItem value="low">Price: Low to High</SelectItem><SelectItem value="high">Price: High to Low</SelectItem></SelectContent></Select></div></div>
    <p className="mb-6 text-xs text-muted-foreground">{visible.length} pieces</p><div className="product-grid pb-12">{visible.map((product) => <ProductCard key={product.id} product={product} />)}</div>{visible.length === 0 && <p className="py-20 text-center text-muted-foreground">No pieces match these filters.</p>}
  </div>; }
