import { HeartOff, ShoppingBag } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/store/product-card";
import { getProduct } from "@/lib/products";
import { useStore } from "@/lib/store-context";
export const Route = createFileRoute("/wishlist")({ head: () => ({ meta: [{ title: "Wishlist — RŌSEN" }, { name: "description", content: "Your saved RŌSEN pieces." }, { property: "og:title", content: "Wishlist — RŌSEN" }, { property: "og:description", content: "Your saved RŌSEN pieces." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: WishlistPage });
function WishlistPage() { const { wishlist, addToCart, toggleWishlist } = useStore(); const saved = wishlist.map(getProduct).filter((product) => product !== undefined); return <div className="site-container"><header className="page-intro border-b"><p className="eyebrow">Saved for later</p><h1 className="mt-4 font-display text-5xl sm:text-6xl">Wishlist</h1></header>{saved.length ? <><div className="product-grid py-10">{saved.map((product) => <div key={product.id}><ProductCard product={product}/><div className="mt-4 flex gap-2"><Button variant="editorial" className="flex-1" onClick={() => { addToCart(product.id); toggleWishlist(product.id); }}><ShoppingBag/> Move to cart</Button><Button variant="outline" size="icon" onClick={() => toggleWishlist(product.id)} aria-label={`Remove ${product.name}`}><HeartOff/></Button></div></div>)}</div></> : <div className="py-24 text-center"><HeartOff className="mx-auto size-8 text-muted-foreground"/><h2 className="mt-5 font-display text-3xl">Nothing saved yet</h2><p className="mt-3 text-muted-foreground">Keep the pieces you love close at hand.</p><Button asChild variant="editorial" size="wide" className="mt-7"><Link to="/shop">Browse the collection</Link></Button></div>}</div>; }
